[project]
name = "pendulum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numba>=0.60.0",
    "numpy>=2.0.2",
    "pillow>=11.1.0",
    "scipy>=1.13.1",
    "toml>=0.10.2",
]
    